name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed
  pull_request_target:
    types: [labeled]

jobs:
  run-workflow-B:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Determine if Workflow B Should Run
        id: check_conditions
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const runId = github.event.workflow_run.id;
            const runData = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            const prNumber = runData.data.pull_requests[0].number;
            const prData = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const labels = prData.data.labels.map(label => label.name);
            if (labels.includes('run-b')) {
              return true;
            }
            return false;

      - name: Check Previous Workflow A Status
        if: github.event_name == 'pull_request_target' && github.event.label.name == 'run-b'
        id: check_previous_run
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Same script as before to check the most recent Workflow A run status

      - name: Run Workflow B
        if: >
          (github.event_name == 'workflow_run' && steps.check_conditions.outputs.result == 'true') ||
          (github.event_name == 'pull_request_target' && steps.check_previous_run.outputs.result == 'true')

        run: echo 'hi'
