# testing out using workflow_run to trigger a workflow from another workflow.
# this will trigger test-b.yml

name: Test A
on:
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  say-things-a:
    runs-on: ubuntu-latest
    steps:
      - name: Run A
        run: echo 'hi'
